-- BanglaRTP Seed Data
-- Run after migrations: psql $DATABASE_URL -f supabase/seed.sql

-- ============ MASJIDS ============
insert into public.masjids (id, name, address, city, phone, website, prayer_times_url, maps_url, description, jummah_time) values
('iar',           'Islamic Association of Raleigh (IAR)',    '808 Atwater St, Raleigh, NC 27607',                   'Raleigh',     '(919) 834-9572', 'https://raleighmasjid.org',       'https://raleighmasjid.org/prayer-times',       'https://maps.google.com/?q=Islamic+Association+of+Raleigh', 'One of the largest Islamic centers in the Triangle.',                       '1:30 PM (Winter) / 2:00 PM (Summer)'),
('icm',           'Islamic Center of Morrisville (ICM)',     '1500 Morrisville Pkwy, Morrisville, NC 27560',        'Morrisville', '(919) 481-9492', 'https://www.icmorrisville.org',   'https://www.icmorrisville.org/prayer-times',  'https://maps.google.com/?q=Islamic+Center+of+Morrisville', 'Serving rapidly growing Muslim community in Morrisville and Cary.',         '1:30 PM'),
('masjid-ar-razzaq', 'Masjid Ar-Razzaq',                    '3309 Fayetteville St, Durham, NC 27707',              'Durham',      '(919) 682-7997', 'https://www.masjidrarrazzaq.com', null,                                          'https://maps.google.com/?q=Masjid+Ar-Razzaq+Durham',       'Welcoming masjid in south Durham serving diverse Muslim communities.',       '1:15 PM'),
('cary-masjid',   'Cary Masjid (Al-Iman)',                   '2100 Kildaire Farm Rd, Cary, NC 27518',               'Cary',        '(919) 467-3727', 'https://www.carymasjid.org',      'https://www.carymasjid.org/prayer-times',     'https://maps.google.com/?q=Cary+Masjid',                   'Serving the Cary Muslim community.',                                        '1:30 PM'),
('masjid-ibrahim','Masjid Ibrahim (ISCF)',                   '4900 Garrett Rd, Durham, NC 27707',                   'Durham',      '(919) 493-7770', 'https://www.iscf.net',            null,                                          'https://maps.google.com/?q=Masjid+Ibrahim+Durham',         'Active community with daily prayers and Islamic school.',                   '1:30 PM')
on conflict (id) do nothing;

-- ============ BUSINESSES (GROCERY) ============
insert into public.businesses (id, name, category, address, city, phone, hours, maps_url, halal_certified, description, approved) values
('halal-meat-cary',      'Halal Meat & Grocery Store',      'grocery', '1931 High House Rd, Cary, NC 27519',            'Cary',        '(919) 467-5858', 'Mon–Sat 9am–8pm, Sun 10am–7pm',     'https://maps.google.com/?q=Halal+Meat+Grocery+Cary',        true,  'Full-service halal meat and grocery. Fresh goat, lamb, chicken butchered on-site.', true),
('raleigh-halal-market', 'Raleigh Halal Market',            'grocery', '2237 Avent Ferry Rd, Raleigh, NC 27606',        'Raleigh',     '(919) 851-1111', 'Daily 10am–9pm',                     'https://maps.google.com/?q=Raleigh+Halal+Market',           true,  'Popular halal grocery near NC State.',                                               true),
('patel-brothers-cary',  'Patel Brothers',                  'grocery', '10040 Green Level Church Rd, Cary, NC 27519',   'Cary',        '(919) 465-4800', 'Daily 9:30am–8:30pm',               'https://maps.google.com/?q=Patel+Brothers+Cary',            false, 'National South Asian grocery chain with excellent selection.',                        true),
('iqbal-halal-foods',    'Iqbal Halal Foods',               'grocery', '1500 Buck Jones Rd, Raleigh, NC 27606',         'Raleigh',     '(919) 851-3337', 'Mon–Sat 10am–8pm, Sun 11am–6pm',    'https://maps.google.com/?q=Iqbal+Halal+Foods+Raleigh',      true,  'Community-favorite halal butcher and grocery.',                                      true),
('india-grocers-durham', 'India Grocers',                   'grocery', '5410 NC-55, Durham, NC 27713',                  'Durham',      '(919) 484-0086', 'Daily 10am–8:30pm',                  'https://maps.google.com/?q=India+Grocers+Durham',           false, 'Well-stocked South Asian grocery near RTP.',                                         true),
('shahi-halal-morrisville','Shahi Halal Meat & Grocery',    'grocery', '200 Morrisville Square Way, Morrisville, NC 27560','Morrisville','(984) 219-2251','Mon–Sat 10am–8pm, Sun 11am–7pm',   'https://maps.google.com/?q=Shahi+Halal+Morrisville',        true,  'Newer halal market in the heart of Morrisville.',                                    true),
('global-bazaar-durham', 'Global Bazaar International Foods','grocery','3622 Shannon Rd, Durham, NC 27707',             'Durham',      '(919) 401-7655', 'Mon–Sat 9am–8pm, Sun 10am–7pm',     'https://maps.google.com/?q=Global+Bazaar+Durham',           false, 'International grocery with South Asian, Middle Eastern, and African products.',      true)
on conflict (id) do nothing;

-- ============ BUSINESSES (RESTAURANTS) ============
insert into public.businesses (id, name, category, address, city, phone, hours, maps_url, cuisine, price_range, halal_certified, description, approved) values
('bangla-curry',         'Bangla Curry',             'restaurant', '1412 Kildaire Farm Rd, Cary, NC 27511',        'Cary',        '(919) 460-7677', 'Mon–Thu 11am–10pm, Fri–Sat 11am–11pm', 'https://maps.google.com/?q=Bangla+Curry+Cary',        'Bangladeshi',   '$$', true,  'Authentic Bangladeshi cuisine — hilsa fish, beef bhuna, kacchi biryani.', true),
('saffron-indian',       'Saffron Indian Cuisine',   'restaurant', '10325 South Square Ct, Durham, NC 27707',     'Durham',      '(919) 484-2000', 'Mon–Fri 11:30am–10pm, Sat–Sun 12–10pm','https://maps.google.com/?q=Saffron+Indian+Durham',    'Indian',        '$$', true,  'Popular upscale Indian restaurant near RTP with halal menu options.',      true),
('bollywood-bistro',     'Bollywood Bistro',         'restaurant', '11721 N Harrison Ave, Morrisville, NC 27560', 'Morrisville', '(919) 469-5400', 'Daily 11am–10pm',                       'https://maps.google.com/?q=Bollywood+Bistro+Morrisville','Indian',      '$$', false, 'Beloved Morrisville institution. Massive lunch buffet is a local favorite.', true),
('kabab-shack-cary',     'Kabab Shack',              'restaurant', '1135 Kildaire Farm Rd, Cary, NC 27511',        'Cary',        '(919) 380-0800', 'Mon–Thu 11am–10pm, Fri–Sun 11am–11pm', 'https://maps.google.com/?q=Kabab+Shack+Cary',         'Pakistani',     '$',  true,  'Fast-casual Pakistani grill. Affordable and delicious.',                   true),
('neomonde-raleigh',     'Neomonde Mediterranean',   'restaurant', '3817 Beryl Rd, Raleigh, NC 27607',             'Raleigh',     '(919) 828-1628', 'Mon–Sat 7am–9pm, Sun 8am–8pm',         'https://maps.google.com/?q=Neomonde+Raleigh',         'Middle Eastern', '$', true,  'Halal-certified since 1977. Shawarma, falafel, fresh pita.',              true),
('hyderabad-house',      'Hyderabad House',          'restaurant', '800 Copeland Oaks Dr, Morrisville, NC 27560', 'Morrisville', '(919) 380-7900', 'Mon–Thu 11am–10pm, Fri–Sun 11am–11pm', 'https://maps.google.com/?q=Hyderabad+House+Morrisville','Indian',      '$$', true,  'Authentic Hyderabadi dum biryani.',                                        true),
('shaheen-pakistani',    'Shaheen Restaurant',       'restaurant', '4325 Glenwood Ave, Raleigh, NC 27612',         'Raleigh',     '(919) 787-8867', 'Mon–Thu 11am–10pm, Fri–Sun 11am–11pm', 'https://maps.google.com/?q=Shaheen+Restaurant+Raleigh','Pakistani',    '$$', true,  'Established Pakistani restaurant with karahi, biryani, haleem.',           true)
on conflict (id) do nothing;

-- ============ EVENTS ============
insert into public.events (id, title, description, date, time, location, organizer, event_type, url, approved) values
('pohela-boishakh-2026', 'Pohela Boishakh – Bangla New Year 1433', 'Celebrate the Bangla New Year with music, dance, and food.', '2026-04-14', '12:00 PM – 7:00 PM', 'Marbles Kids Museum Outdoor Area, Raleigh', 'BANC', 'cultural', 'https://www.bancnc.org', true),
('newcomer-orientation-2026', 'Newcomer Orientation & Welcome Meetup', 'Free orientation for new arrivals covering housing, schools, DMV, and more.', '2026-04-26', '3:00 PM – 6:00 PM', 'Morrisville Community Center, 260 Town Hall Dr, Morrisville', 'TBSNC & BPOCNC', 'educational', null, true),
('professional-networking-2026', 'Bangla Tech & Professional Networking Night', 'Network with Bangladeshi professionals across tech, finance, and healthcare.', '2026-05-09', '6:30 PM – 9:30 PM', 'Google RTP Office, 7000 Louis Stephens Dr, Durham', 'BPOCNC', 'professional', null, true),
('cricket-tournament-2026', 'RTP Bangla Cricket Tournament', 'Annual community cricket tournament.', '2026-05-16', '8:00 AM – 6:00 PM', 'Marla Dorrel Park, Cary, NC', 'BPOCNC', 'sports', null, true),
('eid-ul-adha-2026', 'Eid ul-Adha Community Prayer & Celebration', 'Community Eid prayers followed by breakfast and celebration.', '2026-06-07', '7:00 AM – 1:00 PM', 'Islamic Center of Morrisville (ICM)', 'TBSNC', 'religious', 'https://www.tbsnc.org', true)
on conflict (id) do nothing;

-- ============ PROFESSIONALS ============
insert into public.professionals (id, name, profession, specialty, phone, email, languages, city, practice_name, approved) values
('dr-ahmed',     'Dr. Tariq Ahmed',       'Physician',         'Family Medicine',                           '(919) 555-0101', null,                         array['Bengali','English','Hindi','Urdu'], 'Cary',        'WakeMed Primary Care – Cary',        true),
('dr-rahman',    'Dr. Farzana Rahman',    'Physician',         'Pediatrics',                                '(919) 555-0202', null,                         array['Bengali','English'],               'Morrisville', 'UNC Children''s Primary Care',       true),
('atty-hossain', 'Md. Hossain, Esq.',     'Attorney',          'Immigration Law (H1B, Green Card)',         '(919) 555-0303', 'info@hossainlaw.com',         array['Bengali','English'],               'Raleigh',     'Hossain Law Group',                  true),
('realtor-karim','Nasrin Karim',          'Real Estate Agent', 'Residential – Cary, Morrisville, Apex',    '(919) 555-0404', 'nasrin@carolinarealty.com',   array['Bengali','English'],               'Cary',        'Carolina Realty Partners',           true),
('cpa-chowdhury','Rahul Chowdhury, CPA',  'Accountant / CPA',  'Tax Preparation, Small Business, NRI',     '(919) 555-0505', 'rahul@chowdhurycpa.com',      array['Bengali','English'],               'Durham',      'Chowdhury CPA Services',             true),
('dr-akhter',    'Dr. Shirin Akhter',     'Physician',         'OB/GYN',                                   '(919) 555-0606', null,                         array['Bengali','English','Hindi'],        'Raleigh',     'Duke OB/GYN – South Durham',         true),
('sunshine-dc',  'Sunshine Bangla Daycare','Daycare Provider', 'Ages 6 weeks – 5 years, Bangla immersion', '(919) 555-0707', 'sunshine.daycare.rtp@gmail.com', array['Bengali','English'],            'Morrisville', null,                                 true),
('arif-khan',    'Arif Khan, CFP',        'Financial Advisor', 'Retirement, 401k, Remittance Planning',    '(919) 555-0909', 'arif@khanfinancial.com',      array['Bengali','English'],               'Raleigh',     'Khan Financial Planning',            true)
on conflict (id) do nothing;
